title: Je Vais Craquer — Légal
description: Politique de confidentialité, CGU et mentions légales de l'application Je Vais Craquer
theme: jekyll-theme-minimal
url: "https://ec-voodoo.github.io"
baseurl: "/jevaiscraquer-legal"
